### ISSUE TITLE
第六章没有翻译完

### ISSUE THREAD

**Issue by heistings** [oa414/objc-zen-book-cn#1]
### Designated and Secondary Initializers

有一大段没有翻译，从下面这段开始：

> It should rather be valid to call any designated initializer in the class hierarchy, and it should be guaranteed that all the designated initializer in the class hierarchy are called starting from the furthest ancestor (typically NSObject) down to your class. Practically speaking this means that the first initialization code executed is the furthest ancestor, and then going down to the class hierarchy; giving to all the classes in the hierarchy the chance to do their specific part of initialization. This totally make sense: you want that everything you inherit from your superclass is in an usable state before doing your actual work. Even though it isn't explicitly stated, all the classes in Apple's frameworks are guaranteed to respect this contract and your classes should do the same to be sure to be a good citizen and behave correctly and as expected

**Comment by oa414** [comment]
感谢指正，5-7，10-12 仍未完成翻译。。很多内容只是根据初步理解先转化成中文，待完成之后会一起审定～

**Comment by heistings** [comment]
也感谢您的耐心工作，祝您学运昌隆 👍~
