### ISSUE TITLE
是不是太着急了

### ISSUE THREAD

**Issue by KevinHM** [oa414/objc-zen-book-cn#19]
从Designated initializer开始往下，每一个概念里面，涉及到的知识点，差不多有一半翻译得比较生硬。。。出现很多小错误，有些甚至跟原文意思彻底相反，慢慢来呀，别太急哥们。。。

**Comment by oa414** [comment]
翻译的时候拆成了不同的章节，所以翻译顺序和原文有所不同。

部分概念和表达由于个人技术理解、原文阅读和中文表达等原因确实还有诸多欠妥的地方，感谢指正！有空也会再一次校对和改善。
