### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by heistings** [oa414/objc-zen-book-cn#2]
`There are three different situations that may present when defining a new class:`
- No need to override any initializers
- Overriding designated initializer
- Define a new designated initializer

`当顶一个一个新类的时候有三个不同的解决方法`： 1. 不需要重载任何初始化函数 2. 重载 designated initializer 3. 定义一个新的 designated initializer

**Comment by oa414** [comment]
感谢指正！ 

5，7，10，11，12章以及其他章节部分疑难句子还未完成翻译，很多内容只是追求初步理解打上去的，随后会一起整理审校发布。

**Comment by heistings** [comment]
也感谢你的翻译工作，我是通过你的另一篇文章知道有这一篇文章的。目前正在读原文，感觉颇有收获。

**Comment by oa414** [comment]
嗯，也是最近相对闲下来，发现这篇很不错的文章/小书出了大半年了还没有在很大范围传播，所以一方面仔细阅读加深理解，一方面或许能做一些惠及新手的翻译工作。

**Comment by heistings** [comment]
请问，你是在如何编辑 .md 文件的？clone 到本地的 .md 文件内容看起来密密麻麻。我只能在 github 上查看这些文件。

**Comment by oa414** [comment]
是用 Sublime Text + Markdown 插件

**Comment by KevinHM** [comment]
MacDown的书写体验更好些，个人感觉。

**Comment by heistings** [comment]
@KevinHM Thanks a lot, this one is really helpful. :+1:

**Comment by oa414** [comment]
今天用到 typora 感觉更棒～
http://typora.io/
@KevinHM  @heistings

**Comment by heistings** [comment]
@oa414 感谢。：）表格功能在插入删除方面比较好用，但是在调整顺序的时候比较麻烦，是不是我的使用方式不对？

**Comment by heistings** [comment]
@oa414 [typero](http://typora.io/) 有一个问题，它会对文本做一些它的默认格式化操作，比如 

``````
```objective-c
``````

 会变成

``````
 ``` objective-c 
``````

```
* A
```

会变成

```
- A
```

我感觉它是一个傻瓜式的工具。为了与原文格式尽量一致，暂时还是不要用它了。不过，现在它还处于 Beta 版本，有时间可以直接联系作者提供意见。

**Comment by heistings** [comment]
@oa414 Thank you all the same.:) It's amazing.
