### ISSUE TITLE
关于 Secondary initializer 段落的翻译问题

### ISSUE THREAD

**Issue by oa414** [oa414/objc-zen-book-cn#21]
关于这个 pull-request 提到的翻译问题 #18 ，大家可以在这里讨论下 @KevinHM @heistings

**Comment by heistings** [comment]
将术语翻译成中文怎么样？我还在顺 Naming.

| 术语 | 翻译 |
| :-: | :-: |
| designated initializer | 指定初始化方法 |
| secondary initializer | 间接初始化方法 |

**Comment by heistings** [comment]
> secondary initializer 是一种提供默认值、行为到 designated initializer的方法。

间接初始化方法以默认值调用指定初始化方法。

**Comment by KevinHM** [comment]
赞同heistings的意见,因为最近在接着翻译自己挖的坑"iOS函数反应型编程"，这个项目暂时木有关注了。。。

**Comment by KevinHM** [comment]
但是这里最好保留原英文技术词汇+中文的直译（如间接的初始化方法(secondary initalizer) XXXX (Designated Initializer)指定初始化方法）iOS开发中 很多类的初始化中有NS_DESIGNATED_INITIALIZER这样的编译提示。

**Comment by heistings** [comment]
@KevinHM 这个方法可以，后续尽量使用类似的办法翻译术语，段落中第二次出现的术语不再使用英文。

**Comment by KevinHM** [comment]
@heistings @oa414  我的项目已经弄完了，接下来我们一起来完善这个项目吧！[这是我的项目](https://github.com/KevinHM/FunctionalReactiveProgrammingOniOS)，大家有空帮忙审查下，一些地方有啥不妥的或者错误的欢迎斧正！

**Comment by oa414** [comment]
@KevinHM 翻译很棒。。不过不会有版权问题么。。是不是联系下作者更好

**Comment by KevinHM** [comment]
@oa414 是有版权问题，而且书本身不是开源的，应该不会允许我这么做，所以我只是小范围传阅学习用。。。

**Comment by oa414** [comment]
或许你可以尝试联系下作者能不能得到授权，作者好说话的话或许能允许，没准还能给你中文版本销售的收益。。Ruby 社区就有这样做的：http://railstutorial-china.org/

**Comment by oa414** [comment]
@KevinHM

**Comment by KevinHM** [comment]
@oa414 谢谢提供信息，我尝试一下，能开源就好。

**Comment by heistings** [comment]
@oa414 有几个 pull request 你一直没有合并，如果有问题直接打回；没有问题就合了吧。

**Comment by oa414** [comment]
之前的翻译已经合并，designated initializer 和 secondary initializer 如果翻译的话使用 `直接初始化方法(designated initializer )`，或者直接用 `designated 初始化方法` 这样的形式吧。  没有看到很统一权威的相关术语对照。 @heistings

**Comment by oa414** [comment]
@KevinHM  在译者中加了你的用户名和github链接

**Comment by KevinHM** [comment]
(⊙o⊙)…非常感谢
