### ISSUE TITLE
practice

### ISSUE THREAD

**Issue by heistings** [oa414/objc-zen-book-cn#3]
我感觉 **practice** 这个词的含义应该是`惯例`，或者引申为`编程规范` or `规范`。

> practice的定义
> noun
> the actual application or use of an idea, belief, or method as opposed to theories about such application or use.
> "the principles and practice of teaching"
> 同义词: application, exercise, use, operation, implementation, execution

**Comment by oa414** [comment]
请问你说的稳重是说哪个地方？

**Comment by heistings** [comment]
@oa414 书写错误，我重新编辑一下。
