### ISSUE TITLE
常量extern的写法在Xcode7中编译不通过

### ISSUE THREAD

**Issue by zj159963** [oa414/objc-zen-book-cn#38]
## 在 .h中
# import <UIKit/UIKit.h>

extern NSString *const ZOCCacheControllerDidClearCacheNotification;

@interface ViewController : UIViewController
## 在.m中
# import "ViewController.h"

static NSString \* const ZOCCacheControllerDidClearCacheNotification = @"ZOCCacheControllerDidClearCacheNotification";

@implementation ViewController
## @end

错误信息如下：
Static declaration of "ZOCCacheControllerDidClearChacheNotification" follows non-static declaration.

查询了一下iOS SDK中， 使用类似这个:
UIKIT_EXTERN NSString \* const NSForegroundColorAttributeName
来提供外部使用

猜测，在.m中，实现方式如下
NSString \* const NSForegoundColorAttributeName = @"NSForegoundColorAttributeName";

于是，实验了一下，编译通过：
## 在.h文件中
# import <UIKit/UIKit.h>

UIKIT_EXTERN NSString \* const kKey;

@interface ViewController : UIViewController
## 在.m文件中
# import "ViewController.h"

NSString \* const kKey = @"Key";

@implementation ViewController
## @end 

编译通过，运行拿到数据。
如果命名重复，在外部引用时，定义了相同的名字
    NSString *kKey = @"a";
    NSLog(@"Key: %@",kKey);
这个时候，kKey 是 a。

**Comment by oa414** [comment]
你说的是命名－常量这个小节的内容么？

用 static 声明是因为这样不会在那个声明的 m 文件外暴露，可以作为一个私有的常量，详细的解释参考 http://stackoverflow.com/questions/2092005/when-to-use-static-string-vs-define

翻译的描述是：

```
常量应该在头文件中以这样的形式暴露给外部：

extern NSString *const ZOCCacheControllerDidClearCacheNotification;
并在实现文件中为它赋值。
```

因为紧接着上面的描述，所以会引起误解。事实上如果这样暴露给外部的话，肯定也不能有 static 的声明的。事实上在 NSNotifacation 这一节也有对应的说法。

UIKIT_EXTERN 貌似是私有的，平时开发我们会用 FOUNDATION_EXPORT, 对于不同的平台会有不同的编译输出，不过只是 iOS 上，extern 也是一样的用法。
