### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by twlz0ne** [oa414/objc-zen-book-cn#39]
原文

>  Private properties should be declared in class extensions (_**anonymous categories**_) in the implementation file of a class. Named categories (e.g. `ZOCPrivate`) should never be used unless extending another class.

译文

> 私有属性应该定义在类的实现文件的类的扩展 (_**class extensions**_) 中。不允许在有名字的的 category(如 `ZOCPrivate`）中定义私有属性，除非你扩展其他类。

**Comment by oa414** [comment]
感谢指正！已修改。
