### ISSUE TITLE
一个小错字

### ISSUE THREAD

**Issue by rxdxxxx** [oa414/objc-zen-book-cn#44]
在"属性定义" 一节中
"为了完成一个共有的 getter 和一个私有的 setter，你应该声明公开的属性为 readonly 并且在类扩展总重新定义通用的属性为 readwrite 的。"

类扩展"总"应该是 " 中" 吧, 一个小错字

**Comment by oa414** [comment]
感谢指正！已修正。

**Comment by Thandh** [comment]
We need to ease all porn of the internet and anything racial it will save a
lot of people worldwide please. The government ain't the government in any
country or continent

**Comment by Thandh** [comment]
Off the internet

**Comment by Thandh** [comment]
Last time I ask China to help stop America and in return i saved the Korean
minister from being assassinated

**Comment by Thandh** [comment]
When hacking went viral on America news year 2014

**Comment by Thandh** [comment]
What are hackers for
