### ISSUE TITLE
关于"重载"和"重写"

### ISSUE THREAD

**Issue by DemonsLu** [oa414/objc-zen-book-cn#47]
中文翻译文档中多次提到"重载"这个词，不过根据我个人的理解，它们在文中的意思应该都是"重写"(Override)吧，应该是子类重写父类的方法。OC是没有重载这个特性的 =。=

**Comment by oa414** [comment]
感谢指正！以前学艺不清翻译错了不知道误导了多少人....

抱歉拖了很久才看到和修复，已经在 commit 5f6038a91662683fc9bcbd19d04d810791124bf0  中修复。

**Comment by AAChartModel** [comment]
是的,重载的英文应该是 overload 吧!
