### ISSUE TITLE
It's interesting to understand why do we need to set the value of `self` with the return value of `[super init]` and what happens if we don't do that.

### ISSUE THREAD

**Issue by heistings** [oa414/objc-zen-book-cn#7]
这句话在第5章。
我不确定，这里的 `It's interesting to` 似乎相当于  `It's good to`，你觉得呢？

**Comment by oa414** [comment]
和一个英语系朋友聊了下，感觉应该不是 It's good to。

我的感觉It's interesting to 意思是：对喜欢探寻的开发者来说，深入理解这些内容还是蛮有趣的。但是很难用合适的中文表达。。功底不够。。
